Fixed Parallel Consume JSON oBJECT RETURN

diff --git a/app/build/scripts/app b/app/build/scripts/app
--- a/app/build/scripts/app
+++ b/app/build/scripts/app
@@ -15,8 +15,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# SPDX-License-Identifier: Apache-2.0
-#
 
 ##############################################################################
 #
@@ -57,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -85,8 +83,10 @@ done
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s\n' "$PWD" ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
+
+# Add default JVM options here. You can also use JAVA_OPTS and APP_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +114,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/app.jar:$APP_HOME/lib/gson-2.8.9.jar:$APP_HOME/lib/json-20230618.jar:$APP_HOME/lib/dotenv-java-2.2.0.jar
+CLASSPATH=$APP_HOME/lib/app-plain.jar:$APP_HOME/lib/gson-2.8.9.jar:$APP_HOME/lib/json-20230618.jar:$APP_HOME/lib/dotenv-java-2.2.0.jar:$APP_HOME/lib/spring-boot-starter-web-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-actuator-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-json-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-data-jpa-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-aop-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-jdbc-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-2.7.4.jar:$APP_HOME/lib/spring-boot-actuator-autoconfigure-2.7.4.jar:$APP_HOME/lib/spring-boot-autoconfigure-2.7.4.jar:$APP_HOME/lib/spring-boot-actuator-2.7.4.jar:$APP_HOME/lib/spring-boot-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-logging-2.7.4.jar:$APP_HOME/lib/spring-boot-starter-tomcat-2.7.4.jar:$APP_HOME/lib/jakarta.annotation-api-1.3.5.jar:$APP_HOME/lib/spring-webmvc-5.3.23.jar:$APP_HOME/lib/spring-web-5.3.23.jar:$APP_HOME/lib/spring-data-jpa-2.7.3.jar:$APP_HOME/lib/spring-context-5.3.23.jar:$APP_HOME/lib/spring-aop-5.3.23.jar:$APP_HOME/lib/spring-orm-5.3.23.jar:$APP_HOME/lib/spring-jdbc-5.3.23.jar:$APP_HOME/lib/spring-data-commons-2.7.3.jar:$APP_HOME/lib/spring-tx-5.3.23.jar:$APP_HOME/lib/spring-beans-5.3.23.jar:$APP_HOME/lib/spring-expression-5.3.23.jar:$APP_HOME/lib/spring-core-5.3.23.jar:$APP_HOME/lib/snakeyaml-1.30.jar:$APP_HOME/lib/micrometer-core-1.9.4.jar:$APP_HOME/lib/jakarta.transaction-api-1.3.3.jar:$APP_HOME/lib/jakarta.persistence-api-2.2.3.jar:$APP_HOME/lib/hibernate-core-5.6.11.Final.jar:$APP_HOME/lib/spring-aspects-5.3.23.jar:$APP_HOME/lib/logback-classic-1.2.11.jar:$APP_HOME/lib/log4j-to-slf4j-2.17.2.jar:$APP_HOME/lib/jul-to-slf4j-1.7.36.jar:$APP_HOME/lib/spring-jcl-5.3.23.jar:$APP_HOME/lib/jackson-datatype-jsr310-2.13.4.jar:$APP_HOME/lib/jackson-module-parameter-names-2.13.4.jar:$APP_HOME/lib/jackson-annotations-2.13.4.jar:$APP_HOME/lib/jackson-core-2.13.4.jar:$APP_HOME/lib/jackson-datatype-jdk8-2.13.4.jar:$APP_HOME/lib/jackson-databind-2.13.4.jar:$APP_HOME/lib/tomcat-embed-websocket-9.0.65.jar:$APP_HOME/lib/tomcat-embed-core-9.0.65.jar:$APP_HOME/lib/tomcat-embed-el-9.0.65.jar:$APP_HOME/lib/HdrHistogram-2.1.12.jar:$APP_HOME/lib/LatencyUtils-2.0.3.jar:$APP_HOME/lib/aspectjweaver-1.9.7.jar:$APP_HOME/lib/HikariCP-4.0.3.jar:$APP_HOME/lib/hibernate-commons-annotations-5.1.2.Final.jar:$APP_HOME/lib/jboss-logging-3.4.3.Final.jar:$APP_HOME/lib/byte-buddy-1.12.17.jar:$APP_HOME/lib/antlr-2.7.7.jar:$APP_HOME/lib/jandex-2.4.2.Final.jar:$APP_HOME/lib/classmate-1.5.1.jar:$APP_HOME/lib/jaxb-runtime-2.3.6.jar:$APP_HOME/lib/slf4j-api-1.7.36.jar:$APP_HOME/lib/logback-core-1.2.11.jar:$APP_HOME/lib/log4j-api-2.17.2.jar:$APP_HOME/lib/jakarta.xml.bind-api-2.3.3.jar:$APP_HOME/lib/txw2-2.3.6.jar:$APP_HOME/lib/istack-commons-runtime-3.0.12.jar:$APP_HOME/lib/jakarta.activation-1.2.2.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,13 +133,10 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    if ! command -v java >/dev/null 2>&1
-    then
-        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-    fi
 fi
 
 # Increase the maximum file descriptors if we can.
@@ -147,7 +144,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
+        # shellcheck disable=SC3045 
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
@@ -155,7 +152,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
       '' | soft) :;; #(
       *)
         # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
+        # shellcheck disable=SC3045 
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -200,15 +197,11 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-
-# Add default JVM options here. You can also use JAVA_OPTS and APP_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
-
-# Collect all arguments for the java command:
-#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
-#     and any embedded shellness will be escaped.
-#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
-#     treated as '${Hostname}' itself on the command line.
+# Collect all arguments for the java command;
+#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $APP_OPTS can contain fragments of
+#     shell script including quotes and variable substitutions, so put them in
+#     double quotes to make sure that they get re-expanded; and
+#   * put everything else in single quotes, so that it's not re-expanded.
 
 set -- \
         -classpath "$CLASSPATH" \
